### ISSUE TITLE
Meltdown mérés

### ISSUE THREAD

**Issue by hg2ecz** [haa-zee/proc_speedtest#3]
Érdekességképpen Intel procinál a Meltdown hiba miatt kernel izoláció kikapcsolásával is érdemes lehet a mérést elvégezni. Ehhez a linux bootoláskor a grub-ot futásidőben editálva a kernel sorába "nopti" opciót berakva indítod. Nálam kb. 10% a különbség.

$ time ./proc_speed_test_C2; time ./proc_speed_test_Rust; time pypy ./proc_speed_test.py
Count: 2546753
Error Count: 4

real    0m21,177s
user    0m3,153s
sys     0m17,680s
Count: 2544296
Error count: 1

real    0m22,720s
user    0m4,720s
sys     0m17,657s
Count:  2535716
Error:  1

real    0m34,110s
user    0m10,102s
sys     0m23,354s

# grub futásidőben "nopti" kapcsolóval indítva.
$ dmesg  | grep isola
[    0.000000] Kernel/User page tables isolation: disabled on command line.

$ time ./proc_speed_test_C2; time ./proc_speed_test_Rust; time pypy ./proc_speed_test.py
Count: 2570000
Error Count: 0

real    0m18,839s
user    0m2,252s
sys     0m16,582s
Count: 2570000
Error count: 0

real    0m20,310s
user    0m3,744s
sys     0m16,242s
Count:  2566205
Error:  1

real    0m31,201s
user    0m9,261s
sys     0m21,534s

**Comment by haa-zee** [comment]
Ezt majd kipróbálom, bár ahogy elnéztem az eddigi méréseket... :)

Viszont, ha van időd, kedved és érdekel a pythonos része: átírtam a measure.sh-t measure.py néven Pythonra és kapott pár extrát (csak azt próbálja futtatni, amit tud, hiba esetén kidobja a tesztet a további futtatásokból, paraméter fájlból lehet megadni a teszteket, számlálót is kapott stb.)
Még van hátra pár apróság (output csicsázása, esetleg parancsori kapcsolók bevezetése stb.), de értelme az egész tesztnek továbbra sincs. :)
Mindegy, szórakozásra jó.
